name: CI with Parallel Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3]
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests (Shard ${{ matrix.shard }}/3)
        run: node index.excel.js --excel=input/input.xlsx --shard=${{ matrix.shard }}/3
      
      - name: Upload shard results
        uses: actions/upload-artifact@v4
        with:
          name: shard-${{ matrix.shard }}
          path: report/project-shard-${{ matrix.shard }}-3.json
          retention-days: 1

  merge-results:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Download all shards
        uses: actions/download-artifact@v4
        with:
          path: report
          pattern: shard-*
          merge-multiple: true
      
      - name: Merge shards
        run: node merge-shards.js
      
      - name: Upload final report
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: report/project.json
